name: Build iOS Tweak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: macos-setup/setup-xcode@v1

    - name: Build tweak
      run: |
        cd TesteTweak
        make
